/* =========================================================
   06_dq_and_ops.sql
   Data quality checks + operational recovery
   ========================================================= */

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_CDC;
USE SCHEMA AIRLINE_DL.UTIL;

CREATE OR REPLACE TABLE UTIL.DQ_RESULTS (
    RUN_TS     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    TEST_NAME  VARCHAR,
    TARGET     VARCHAR,
    FAIL_COUNT NUMBER,
    STATUS     VARCHAR
);

/* Every data quality test is the same shape:
   a SELECT that returns the ROWS THAT BREAK THE RULE. Zero rows = pass.
   That is literally all a dbt test compiles to. */

CREATE OR REPLACE PROCEDURE UTIL.SP_RUN_DQ()
RETURNS STRING LANGUAGE SQL AS
$$
BEGIN
  -- unique PK
  INSERT INTO UTIL.DQ_RESULTS (TEST_NAME, TARGET, FAIL_COUNT, STATUS)
  SELECT 'unique_booking_id', 'SILVER.BOOKING', COUNT(*), IFF(COUNT(*)=0,'PASS','FAIL')
  FROM (SELECT BOOKING_ID FROM SILVER.BOOKING GROUP BY 1 HAVING COUNT(*)>1);

  -- not null PK
  INSERT INTO UTIL.DQ_RESULTS (TEST_NAME, TARGET, FAIL_COUNT, STATUS)
  SELECT 'not_null_booking_id', 'SILVER.BOOKING', COUNT(*), IFF(COUNT(*)=0,'PASS','FAIL')
  FROM SILVER.BOOKING WHERE BOOKING_ID IS NULL;

  -- accepted values
  INSERT INTO UTIL.DQ_RESULTS (TEST_NAME, TARGET, FAIL_COUNT, STATUS)
  SELECT 'accepted_booking_status', 'SILVER.BOOKING', COUNT(*), IFF(COUNT(*)=0,'PASS','FAIL')
  FROM SILVER.BOOKING WHERE BOOKING_STATUS NOT IN ('CONFIRMED','PENDING','CANCELLED');

  -- referential integrity
  INSERT INTO UTIL.DQ_RESULTS (TEST_NAME, TARGET, FAIL_COUNT, STATUS)
  SELECT 'fk_claim_to_booking', 'SILVER.CLAIM', COUNT(*), IFF(COUNT(*)=0,'PASS','FAIL')
  FROM SILVER.CLAIM c
  LEFT JOIN SILVER.BOOKING b ON b.BOOKING_ID = c.BOOKING_ID
  WHERE b.BOOKING_ID IS NULL AND NOT c.IS_DELETED;

  -- business rule
  INSERT INTO UTIL.DQ_RESULTS (TEST_NAME, TARGET, FAIL_COUNT, STATUS)
  SELECT 'net_revenue_not_negative', 'GOLD.BOOKING_FACT', COUNT(*), IFF(COUNT(*)=0,'PASS','WARN')
  FROM GOLD.BOOKING_FACT WHERE NET_REVENUE < 0;

  -- reconciliation: no cancelled/deleted booking may reach GOLD
  INSERT INTO UTIL.DQ_RESULTS (TEST_NAME, TARGET, FAIL_COUNT, STATUS)
  SELECT 'gold_excludes_cancelled', 'GOLD.BOOKING_FACT', COUNT(*), IFF(COUNT(*)=0,'PASS','FAIL')
  FROM GOLD.BOOKING_FACT g
  JOIN SILVER.BOOKING s ON s.BOOKING_ID = g.BOOKING_ID
  WHERE s.IS_DELETED OR s.BOOKING_STATUS = 'CANCELLED';

  RETURN 'DQ complete';
END;
$$;

CALL UTIL.SP_RUN_DQ();
SELECT * FROM UTIL.DQ_RESULTS ORDER BY RUN_TS DESC;

-- Pipeline audit trail
SELECT * FROM UTIL.PIPELINE_LOG ORDER BY LOG_TS DESC;

-- Freshness / SLA
CREATE OR REPLACE VIEW UTIL.V_FRESHNESS AS
SELECT 'SILVER.BOOKING' AS obj, MAX(UPDATED_AT) AS last_update,
       DATEDIFF('minute', MAX(UPDATED_AT), CURRENT_TIMESTAMP()) AS lag_min
FROM SILVER.BOOKING
UNION ALL
SELECT 'GOLD.BOOKING_FACT', MAX(LOAD_TS),
       DATEDIFF('minute', MAX(LOAD_TS), CURRENT_TIMESTAMP())
FROM GOLD.BOOKING_FACT;

SELECT * FROM UTIL.V_FRESHNESS;


/* =========================================================
   OPERATIONS
   ========================================================= */

-- Snowpipe health. lastReceivedMessageTimestamp NULL = notifications not arriving.
SELECT SYSTEM$PIPE_STATUS('RAW.PIPE_BOOKING');

-- Load errors
SELECT * FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
      TABLE_NAME => 'AIRLINE_DL.RAW.BOOKING',
      START_TIME => DATEADD(hour,-4,CURRENT_TIMESTAMP())))
ORDER BY LAST_LOAD_TIME DESC;

-- Task failures
SELECT NAME, STATE, SCHEDULED_TIME, ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
      SCHEDULED_TIME_RANGE_START => DATEADD(day,-1,CURRENT_TIMESTAMP())))
WHERE STATE != 'SUCCEEDED' ORDER BY SCHEDULED_TIME DESC;

-- Pruning efficiency (Day 1 recap: micro-partitions)
SELECT QUERY_ID, TOTAL_ELAPSED_TIME/1000 secs, PARTITIONS_SCANNED, PARTITIONS_TOTAL, QUERY_TEXT
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(
      END_TIME_RANGE_START => DATEADD(hour,-2,CURRENT_TIMESTAMP())))
WHERE WAREHOUSE_NAME='WH_CDC' ORDER BY secs DESC LIMIT 10;

-- Time Travel: "the 6am batch corrupted SILVER"
SELECT COUNT(*) FROM SILVER.BOOKING AT(OFFSET => -600);   -- 10 minutes ago
-- CREATE OR REPLACE TABLE SILVER.BOOKING AS SELECT * FROM SILVER.BOOKING AT(OFFSET => -600);

-- Zero-copy clone for debugging without touching prod
CREATE OR REPLACE DATABASE AIRLINE_DL_DEBUG CLONE AIRLINE_DL;
DROP DATABASE AIRLINE_DL_DEBUG;


/* =========================================================
   CLEANUP - always run at the end of a session
   ========================================================= */
ALTER TASK UTIL.TSK_UNLOAD          SUSPEND;
ALTER TASK GOLD.TSK_LOAD_GOLD       SUSPEND;
ALTER TASK SILVER.TSK_LOAD_SILVER   SUSPEND;
ALTER WAREHOUSE WH_CDC SUSPEND;
