/* =========================================================
   07_reset_and_rerun.sql
   Wipe the data and replay the whole pipeline end to end.
   Use this to practise, or to re-demo cleanly.
   ========================================================= */

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_CDC;
USE SCHEMA AIRLINE_DL.RAW;

/* ---------- 1. Reset all data (keeps objects) ---------- */
TRUNCATE TABLE RAW.BOOKING;
TRUNCATE TABLE RAW.RESERVATION;
TRUNCATE TABLE RAW.CLAIM;
TRUNCATE TABLE SILVER.BOOKING;
TRUNCATE TABLE SILVER.RESERVATION;
TRUNCATE TABLE SILVER.CLAIM;
TRUNCATE TABLE GOLD.BOOKING_FACT;
TRUNCATE TABLE UTIL.PIPELINE_LOG;

-- Recreate the streams so their offsets reset to "now"
CREATE OR REPLACE STREAM SILVER.STR_BOOKING     ON TABLE RAW.BOOKING     APPEND_ONLY = TRUE;
CREATE OR REPLACE STREAM SILVER.STR_RESERVATION ON TABLE RAW.RESERVATION APPEND_ONLY = TRUE;
CREATE OR REPLACE STREAM SILVER.STR_CLAIM       ON TABLE RAW.CLAIM       APPEND_ONLY = TRUE;
CREATE OR REPLACE STREAM GOLD.STR_SILVER_BOOKING ON TABLE SILVER.BOOKING;


/* ---------- 2. FULL LOAD ----------
   Snowpipe remembers file names for 14 days, so a plain REFRESH will skip
   files it already loaded. On a replay use COPY with FORCE instead. */
COPY INTO RAW.BOOKING
  (BOOKING_ID, PASSENGER_ID, FLIGHT_NUMBER, ORIGIN, DESTINATION, BOOKING_TS,
   BOOKING_STATUS, FARE_AMOUNT, CURRENCY, CHANNEL, CHANGE_OPER, CHANGE_SEQ, CHANGE_TS, SRC_FILE)
FROM (SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13, METADATA$FILENAME
      FROM @UTIL.STG_LANDING/fullload/)
PATTERN = '.*booking.*[.]csv' FILE_FORMAT = (FORMAT_NAME = UTIL.FF_CSV) FORCE = TRUE;

COPY INTO RAW.RESERVATION
  (RESERVATION_ID, BOOKING_ID, SEAT_NUMBER, CABIN_CLASS, RESERVATION_STATUS,
   CHECKED_IN_FLAG, UPDATED_TS, CHANGE_OPER, CHANGE_SEQ, CHANGE_TS, SRC_FILE)
FROM (SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10, METADATA$FILENAME
      FROM @UTIL.STG_LANDING/fullload/)
PATTERN = '.*reservation.*[.]csv' FILE_FORMAT = (FORMAT_NAME = UTIL.FF_CSV) FORCE = TRUE;

COPY INTO RAW.CLAIM
  (CLAIM_ID, BOOKING_ID, CLAIM_TYPE, CLAIM_STATUS, CLAIM_AMOUNT, FILED_TS, SETTLED_TS,
   CHANGE_OPER, CHANGE_SEQ, CHANGE_TS, SRC_FILE)
FROM (SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10, METADATA$FILENAME
      FROM @UTIL.STG_LANDING/fullload/)
PATTERN = '.*claim.*[.]csv' FILE_FORMAT = (FORMAT_NAME = UTIL.FF_CSV) FORCE = TRUE;

CALL SILVER.SP_LOAD_SILVER();
CALL GOLD.SP_LOAD_GOLD();

SELECT COUNT(*) AS gold_after_fullload FROM GOLD.BOOKING_FACT;


/* ---------- 3. HOURLY CDC BATCH ---------- */
COPY INTO RAW.BOOKING
  (BOOKING_ID, PASSENGER_ID, FLIGHT_NUMBER, ORIGIN, DESTINATION, BOOKING_TS,
   BOOKING_STATUS, FARE_AMOUNT, CURRENCY, CHANNEL, CHANGE_OPER, CHANGE_SEQ, CHANGE_TS, SRC_FILE)
FROM (SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13, METADATA$FILENAME
      FROM @UTIL.STG_LANDING/cdc/)
PATTERN = '.*booking.*[.]csv' FILE_FORMAT = (FORMAT_NAME = UTIL.FF_CSV) FORCE = TRUE;

COPY INTO RAW.RESERVATION
  (RESERVATION_ID, BOOKING_ID, SEAT_NUMBER, CABIN_CLASS, RESERVATION_STATUS,
   CHECKED_IN_FLAG, UPDATED_TS, CHANGE_OPER, CHANGE_SEQ, CHANGE_TS, SRC_FILE)
FROM (SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10, METADATA$FILENAME
      FROM @UTIL.STG_LANDING/cdc/)
PATTERN = '.*reservation.*[.]csv' FILE_FORMAT = (FORMAT_NAME = UTIL.FF_CSV) FORCE = TRUE;

COPY INTO RAW.CLAIM
  (CLAIM_ID, BOOKING_ID, CLAIM_TYPE, CLAIM_STATUS, CLAIM_AMOUNT, FILED_TS, SETTLED_TS,
   CHANGE_OPER, CHANGE_SEQ, CHANGE_TS, SRC_FILE)
FROM (SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10, METADATA$FILENAME
      FROM @UTIL.STG_LANDING/cdc/)
PATTERN = '.*claim.*[.]csv' FILE_FORMAT = (FORMAT_NAME = UTIL.FF_CSV) FORCE = TRUE;

SELECT CHANGE_OPER, COUNT(*) FROM RAW.BOOKING GROUP BY 1;   -- I / U / D

CALL SILVER.SP_LOAD_SILVER();
CALL GOLD.SP_LOAD_GOLD();
CALL UTIL.SP_UNLOAD_GOLD();
CALL UTIL.SP_RUN_DQ();


/* ---------- 4. Prove it worked ---------- */
-- BK1011: inserted then updated in the SAME batch. Fare must be 910.00, not 880.00.
SELECT BOOKING_ID, FARE_AMOUNT, CHANGE_SEQ FROM SILVER.BOOKING WHERE BOOKING_ID='BK1011';

-- BK1005: deleted at source -> soft deleted in SILVER, absent from GOLD
SELECT 'silver' lyr, IS_DELETED::VARCHAR v FROM SILVER.BOOKING WHERE BOOKING_ID='BK1005'
UNION ALL
SELECT 'gold', COUNT(*)::VARCHAR FROM GOLD.BOOKING_FACT WHERE BOOKING_ID='BK1005';

-- BK1004: was PENDING, updated to CONFIRMED -> should now be in GOLD
SELECT * FROM GOLD.BOOKING_FACT WHERE BOOKING_ID='BK1004';

-- RAW must be empty (truncate-and-load)
SELECT 'raw booking' t, COUNT(*) c FROM RAW.BOOKING;

SELECT * FROM UTIL.PIPELINE_LOG ORDER BY LOG_TS;
SELECT * FROM UTIL.DQ_RESULTS ORDER BY RUN_TS DESC;
SELECT * FROM GOLD.V_DAILY_ROUTE ORDER BY BOOKING_DATE, ROUTE;
